### ISSUE TITLE
Error message if no entries are present in the broker

### ISSUE THREAD

**Issue by emmelmann-fokus** [reTHINK-project/dev-catalogue#12]
If you access the catalogue at:

https://catalogue.powercommunication.rethink.orange-labs.fr/.well-known/hyperty

you get right now the following error message:

HTTP ERROR: 500

Problem accessing /.well-known/hyperty. Reason:

    java.lang.NullPointerException

It is possible that the reason is that a catalogue-database did *not* populate any entries in the catalogue broker.  

Please verify the behavior of the broker in case no database is attached and in case a database does not populate any entries.

We should return a valid response.

**Comment by sbecot** [comment]
If you tell me where I can find them I can send you the logs.

**Comment by Endebert** [comment]
Fixed
