### ISSUE TITLE
Re-Read config upon signal

### ISSUE THREAD

**Issue by emmelmann-fokus** [reTHINK-project/dev-catalogue#15]
idea for enhancement of the catalogue-database:

Upon receiving a signal, re-read the hyperty etc. object (i.e do not only read them upon starting the program).

May be considered in the next update (after May/June milestones).

**Comment by Endebert** [comment]
Feature added in 1.1.0.

Databases can be restarted with the broker http interface, using either `/.well-known/restart` (restarts all connected databases) or `/.well-known/restart/<endpoint>`. The database(s) will unregister and restart, re-reading the catalogue objects folder while doing so.
