### ISSUE TITLE
sourceCode.js

### ISSUE THREAD

**Issue by sbecot** [reTHINK-project/dev-catalogue#17]
In the [guide](https://github.com/reTHINK-project/dev-catalogue/blob/master/doc/getting_started/usage_guide.md) you mention that sources are included in a sourceCode.js , but the Dataschema objects are json objects, not Javascript.
Do I have to include sourceCode.js, sourceCode.json? Should it be an exception?

**Comment by Endebert** [comment]
You can include your schema as sourceCode.json. The current implementation takes the sourceCode file independently of its file extension.

I will update the guide accordingly, thanks for the feedback.
