### ISSUE TITLE
Prepare new release 1.1.0

### ISSUE THREAD

**Issue by emmelmann-fokus** [reTHINK-project/dev-catalogue#19]
Just a placeholder to collect things that will be therein:

* bugfix in code that causes broker to stall on some machines
* new docker image illustrating how to derive your own "database image" that illustrates how to deploy personal catalogue objects in a dedicated image
* HelloWorld docker file (database added)  --> this should be moved into the standard rethink database image

**Comment by Endebert** [comment]
[Released](https://github.com/reTHINK-project/dev-catalogue/releases/tag/1.1.0). complete changelog:

* Updated leshan version to 0.1.11-M10
* updated model (accessControlPolicy & scheme not mandatory anymore)
* added ability to restart all connected databases, or a specific one, using either '/.well-known/restart' or '/.well-known/restart/<endpoint>'
* renamed folder for idp proxy object from "idpproxy" to "idp-proxy" (how you specify it in URL)
* improved concurrency stability
* Broker & Database respond faster if the response is large
* added -v option to broker & database to increase log level to DEBUG
* colored logging
* Catalogue Broker
  * included rethink-catalogue-test into Catalogue Broker, it is the default website for the Broker now
  * updated test website to automatically get list of instances if type is selected
  * minor changes to broker responses, tries to eliminate stringified jsons in json
  * fixed bug in broker that resulted in a map getting duplicate entries and growing indefinitely on every client update
  * broker may now respond with appropriate error code if an object was not found, or another kind of error occurred
  * removed coap northbound interface from Broker
  * added alias for -sslport option for Broker, called -httpsport or -hs
  * added ability to get list of connected clients using /.well-known/client
  * added ability to do a more fine grained request, e.g. https://localhost/.well-known/sourcepackage/9819113587321/sourceCode/attr2/list (might come in handy with sourceCode as json)
  * added options for setting http and coap host name
* Catalogue Database
  * set default database lifetime to 60s
  * added -lifetime option for Database, setting the interval of sending keep-alives
  * added -endpoint option to set database endpoint name
  * added options for setting coap(s) host name and port
  * fixed database initialization failing if there is no instance for a model
