### ISSUE TITLE
How i set the database to comunicate with broker

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-catalogue#22]
Hi,

I'm configuring our test bed with catalogue docker files, and I have some difficulties to make it work, some one can help me?

I'm doing the following:
1. Start the catalogue-broker, expose the port 443
2. Start the catalogue-database, and expose the port 9080

But in the log of catalogue-database I get always the same message:
```shell
2016-04-06 16:55:32,045 INFO  CatalogueDatabase Registering on localhost/127.0.0.1:5683...
2016-04-06 16:56:36,777 WARN  CatalogueDatabase Registration request timeout
```
My doubt is, how I tell the catalogue database here the broker is?

All other dockers are running correctly, even, the communication with vertx and domain registry;

Thanks

**Comment by Endebert** [comment]
First please make sure you have the most current version of the docker images. Are you by any chance running the docker images in a virtual machine? We recently identified and fixed a bug in such an environment, that should not occur anymore with the current images.

Secondly, Are the broker & database running on the same machine? If so, localhost should work. Maybe there's a problem with a firewall? Unless you changed the coap port of the broker, the broker needs to be reachable on port 5683.

If above suggestions don't solve the problem, please attach logs of the broker and database. And the commands you launch the docker images with might be helpful, too.

**Comment by emmelmann-fokus** [comment]
@vitormsilva 

thanks for this feedback.  This is exactly what we need.  Please have a look at

https://bscw.rethink-project.eu/bscw/bscw.cgi/34081

it is a snapshot of the sections I work on, so it is not yet integrated in d6.1  but the section on how to set up the catalogue, both in a stand alone and in a "testbed / distributed" environment is finished.

Don't hesitate to contact me if you have further questions or suggestions on how to improve the clarity of sections. I appreciate any effort to integrate each partner's components.  This task is urgently needed as seen in WP6.

Best

Marc

**Comment by vitormsilva** [comment]
@emmelmann-fokus and @Endebert,

Thanks for a quick answer;

@Endebert,

> First please make sure you have the most current version of the docker images.....

Yes, i make a pull before running the dockers;

> Secondly, Are the broker & database running on the same machine? If so, localhost should work. Maybe there's a problem with a firewall? Unless you changed the coap port of the broker, the broker needs to be reachable on port 5683.

Is in the same machine, with the same network but in different dockers.

![hybroker](https://cloud.githubusercontent.com/assets/10596749/14349064/4e28fda8-fcb8-11e5-89d4-d3719c96e6b7.png)


> If above suggestions don't solve the problem, please attach logs of the broker and database. And the commands you launch the docker images with might be helpful, too.

i launching the dockers with this:
**catalogue-broker**
```shell
 sudo docker run --net mynet123 --ip=172.18.0.8 --expose=443 --expose=5683 --name="catalogue-broker" rethink/catalogue-broker 2> /tmp/catalogue-broker.err 1> /tmp/catalogue-broker.out &
```
**catalogue-database**
```shell
sudo docker run --net mynet123 --ip=172.18.0.9 --expose=5683 --name="catalogue-database" rethink/catalogue-database 2> /tmp/catalogue-database.err 1> /tmp/catalogue-database.out &
```
**catalogue-test-client**
```shell
sudo docker run --net mynet123 --ip=172.18.0.10 --expose=8090 rethink/catalogue-test-client 2> /tmp/catalogue-test-client.err 1> /tmp/catalogue-test-client.out &
```

the logs are the same, i put before:
![screenshot from 2016-04-07 11-21-46](https://cloud.githubusercontent.com/assets/10596749/14348493/bff7c27e-fcb4-11e5-833a-1bfb6e1c2adc.png)


@emmelmann-fokus,

I looked for your proposal, and I think we have the same as you, but not automatized;

But if I doing something wrong, please tell me.

Thanks;

**Comment by emmelmann-fokus** [comment]
Hi,

the difference is that the tutorials are using the --net=host option of docker.  Hence, the docker instance shares the network IF with the hosting system.

The way you are using docker is in fact similar to setting up the broker & database on different machines with different IPs.  So localhost cannot work as you use the standard docker behavior to create two virtualized, completely separated machines.

You need to specify the port the IP of host that the broker runs on (-h option).  For your set-up, you will also have to specify the -d option with catalogue.hybroker.rethink.....

Look at the tutorial in the  D6.1 update that explains the "complex testbed setup", not the stand alone setup.  That will address your issues.

Also, I remember that I had some issues with not using the --net=host option.  There were some issues with docker regarding passing in and outgoing connections.  The --net=host option worked like charm, so this is the way we set up the environment in order to isolate reThink specific issues in the components form any docker-related issues.

Cheers,

Marc

**Comment by vitormsilva** [comment]
Hi,

It works, i think.

I used a network container to make the catalogue-database running in the same network than catalogue-broker and use 127.0.0.1 like a localhost..

I will analyse better and see if all it's working right.

**Comment by emmelmann-fokus** [comment]
Excellent.  Just send an e-mail if you need further help.  We can Skype to find a quick solution.
