### ISSUE TITLE
Default protocolstub catalogue-database is not replaced by our

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-catalogue#28]
Hi @Endebert,

I'm start configure the testbed and for that, i push the common catalogue database objects, and i delete in [dev-catalogue/docker/catalogue-database-reTHINKdefault/catalogue_objects/](https://github.com/reTHINK-project/dev-catalogue/tree/master/docker/catalogue-database-reTHINKdefault/catalogue_objects) the protocolstub folder, because the default protocolstub is specific of each partner;

So, the problem is, when I load my default protocolstub from [here](https://github.com/reTHINK-project/testbeds/tree/master/nodes/PT-node/catalogue-database), doesn't replace the default, and our doesn't appear.

**Comment by emmelmann-fokus** [comment]
Hi,

we have to distinguish between protocol stubs (of which several can be in the global catalogue), and the "default protosutb" which is specific to each domain / partner.

Not sure if we should delete the entire protocol sub folder ?

**Comment by Endebert** [comment]
@vitormsilva I just tried it and it works on my end as intended. Could you please provide more information like logs, and maybe your directory tree?

**Comment by vitormsilva** [comment]
I think the problem is solved, I don't delete the default protocolstub like Marc said;

Closing issue;
