### ISSUE TITLE
Can't start catalogue-database-reTHINKdefault

### ISSUE THREAD

**Issue by sbecot** [reTHINK-project/dev-catalogue#31]
After getting the dev-catalogue folder from git, I run   
`docker build -t rethink/catalogue-database-default .  `
then  
 `docker run -d -it --name="catalogue-database2" rethink/catalogue-database-default -h 172.17.0.6 -d catalogue.powercommunication.rethink.orange-labs.fr   `
But the catalogue crashes. I get this log:  
`2016-06-07 13:54:52,248 I CatalogueDatabase  Starting Catalogue Database...  `
`2016-06-07 13:54:52,249 I CatalogueDatabase  Catalogue Broker host name: 172.17.0.6   `
`2016-06-07 13:54:52,250 I CatalogueDatabase  Catalogue Broker CoAP port: 5683  `
`2016-06-07 13:54:52,250 I CatalogueDatabase  Catalogue Objects location: /opt/reTHINK/catalogue/catalogue_objects  `
`2016-06-07 13:54:52,477 E CatalogueDatabase  Unable to start Catalogue Database   
 eu.rethink.catalogue.database.exception.CatalogueObjectParsingException: No model ID found for folder '/opt/reTHINK/catalogue/catalogue_objects/idpproxy'  `
`        at eu.rethink.catalogue.database.CatalogueDatabase.parseObjects(CatalogueDatabase.java:407) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]`
`        at eu.rethink.catalogue.database.CatalogueDatabase.start(CatalogueDatabase.java:318) ~[rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]`
`        at eu.rethink.catalogue.database.CatalogueDatabase.main(CatalogueDatabase.java:267) [rethink-catalogue-database-1.1.0-jar-with-dependencies.jar:?]
`

**Comment by sbecot** [comment]
Well, seems that the git pull changed the idp-proxy was named idpproxy on my VM. I changed this and it fixed the pb. The question is why the git pull didn't rename ipdproxy forder?

**Comment by Endebert** [comment]
Hi @sbecot, thanks for the feedback. Are you working with the dev branch? I fixed the folder names in the master branch, but just noticed that until now I forgot to merge those changes into the dev branch. Sorry.

**Comment by sbecot** [comment]
Right, I'm on the dev branch, that is the reason.
