### ISSUE TITLE
How is chosen default runtime when there is no default runtime?

### ISSUE THREAD

**Issue by sbecot** [reTHINK-project/dev-catalogue#34]
Trying to setup a simple application, we're experimenting some problems.
Application is deployed here: https://powercommunication.rethink.orange-labs.fr/  
Catalogue is deployed here: https://catalogue.powercommunication.rethink.orange-labs.fr/  
The default catalogue https://github.com/reTHINK-project/dev-catalogue/tree/dev/docker/catalogue-database-reTHINKdefault was provided by a Runtime that I changed to get the last Runtime version (all are versioned 1.0). Well, it seems that the build includes also the FirstRuntime.  
When I want to upload a runtime, the rethink.js choose to get the default one: https://catalogue.powercommunication.rethink.orange-labs.fr/.well-known/runtime/default .  
The problem is that there is no default runtime in my catalogue so the one chosen is not under my control. If I rename Runtime in default, then it works.  
Couldn't we avoid to name the default, by adding a parameter pointing on default? Or a link?

**Comment by KCorre** [comment]
**Other related remarks**

Same issue for protoStub and IDP-Proxy (at least).

"default" should not be separate objects but pointers to "real" objects. Or at least that should be an option:
* making a pointer "default" to another object does not make any difference. Probably because the object name is not "default" (inside the Json).
* even though "default" request results in a response, the "default" object does not appear in the catalogue test page. https://catalogue.powercommunication.rethink.orange-labs.fr/

**Comment by Endebert** [comment]
I agree with your points and will add a launch option where you can set the default hyperty/runtime/etc.

However, this means that I will also implement an error response when requesting a default hyperty/runtime/etc. and none as been set. This will probably break some current environments, so we will have to make sure everyone gets notified of the change.

**Comment by emmelmann-fokus** [comment]
@Endebert, can you send an e-mail to "all@rethink-project.eu" notifying them on this issue and the intended fix as it might break existing deployments.

Please request objections to the fix and if none has been received within 10 day, proceed with the implementation.

**Comment by Endebert** [comment]
@emmelmann-fokus I will put the fix into the dev branch and notify them of the change, and after a period of time (and if no objections have been raised) I will merge it into the master branch and create a new release.

**Comment by Endebert** [comment]
[I just pushed a commit that implements the behaviour discussed in this issue. ](https://github.com/reTHINK-project/dev-catalogue/commit/33f50edcd489046eece9516612d147c8cbc48fd0)

What has changed?

1. You can set a default instance with the new option "-default" when starting the broker. You can use the option several times to set a default instance for each type, like this:

  ```
  -default hyperty/myHyperty -default protocolstub:myProtostub -default runtime=myRuntime
  ```
  As you can see, you declare a `<type>:<instanceName>` mapping with that option. As a delimiter you can use `/`, `:`, or `=`, as shown in the example.

2. Regarding Catalogue Objects, you cannot define a default instance by calling it "default", i.e. have a folder in catalogue_objects that is named "default", like `/runtime/default`. The Catalogue Database will skip this folder and print a warning message notifying you about it.

  __This means that you have to adapt the catalogue objects contained in `/docker/catalogue-database-reTHINK-HelloWorld` and `/docker/catalogue-database-reTHINKdefault`__

3. If requesting a default instance from the Catalogue Broker using the http interface, e.g. `/.well-known/hyperty/default`, and no default instance was defined when starting the Catalogue Broker, the Catalogue Broker will respond with an error message.

4. It is now possible to request the default instance for a certain type using the Catalogue Broker Test Page.

Please provide feedback and adapt the necessary folders. As mentioned by @emmelmann-fokus, unless this feature has introduced new bugs, it will be merged in to the master branch and a new release will be published in about 10 days.

**Comment by sbecot** [comment]
Well, changing the /docker/catalogue-database-reTHINKdefault is not enough: it is based on the root catalogue database that already has a default and FirstProtostub embedded.

**Comment by sbecot** [comment]
Another remark: I can understand what's a default runtime, a default protostub for a dedicated platform, but what means a default hyperty?

**Comment by emmelmann-fokus** [comment]
> Well, changing the /docker/catalogue-database-reTHINKdefault is not enough: it is based on the root catalogue database that already has a default and FirstProtostub embedded.

The default objects in the images should be ignored with the new version. So having them in the images does not effect the new functionality while we clean up the existing images, i.e., delete the default objects in there.

**Comment by emmelmann-fokus** [comment]
> Another remark: I can understand what's a default runtime, a default protostub for a dedicated platform, but what means a default hyperty?

This is something we need to discuss in WP3.  The agreed resource paths that the catalogue has to support specifies a "default" for each kind of resource. But with the new version of the catalogue, it is up to the user to decide for which resource to provide a "default" object.  I know that does not address your concern; and I agree with your question.

**Comment by Endebert** [comment]
> Well, changing the /docker/catalogue-database-reTHINKdefault is not enough: it is based on the root catalogue database that already has a default and FirstProtostub embedded.

Since @emmelmann-fokus [also created an issue about it](https://github.com/reTHINK-project/dev-catalogue/issues/35), I will go ahead and remove all objects that are named default.

> Another remark: I can understand what's a default runtime, a default protostub for a dedicated platform, but what means a default hyperty?

When I add features like this, I try to be as generic as possible. The Catalogue treats each type equally, so it would not make sense to artificially limit this feature to only a few types. I provided the example only to illustrate that you can use the option several times and with a different delimiter.

**Comment by Endebert** [comment]
I just merged the dev branch into the master branch, that includes the new way of defining default hyperties/protosubs/etc.

Therefore I'm closing this issue. If you find any issues with the new version, don't hesitate to create new issues
