### ISSUE TITLE
Missing documentation for local deployment

### ISSUE THREAD

**Issue by jboulmal** [reTHINK-project/dev-catalogue#37]
We have noticed a lack of information on how to deploy and configure this catalogue locally ?
We share this concern with different contributors in the rethink project ?

**Comment by Endebert** [comment]
I don't see the problem. In the main readme, it is stated:

> Please refer to the [documentation](https://github.com/reTHINK-project/dev-catalogue/tree/master/doc) section for further information.

There you can find both an [installation](https://github.com/reTHINK-project/dev-catalogue/blob/master/doc/getting_started/installation_guide.md) and [usage](https://github.com/reTHINK-project/dev-catalogue/blob/master/doc/getting_started/usage_guide.md) guide, together they should provide you with all the information you need.

**Comment by jboulmal** [comment]
yes, I agree with you about the README, but it's not clear which components are mandatory. how it works ?

**Comment by emmelmann-fokus** [comment]
Hi @jboulmal ,

in short: you must have one catalogue-broker deployed and at least one catalogue-database.

Have you had a look at the deliverable D6.1 which describes the deployment of testbed infrastructures?
Maybe you can give a detailed comment on the therein contained description.

https://bscw.rethink-project.eu/bscw/bscw.cgi/d35609/D6.1%20Testbed%20specification.pdf

Best,

Marc

**Comment by jboulmal** [comment]
Thanks for you help.
I have had a look to D6.1. I'll check it out.
Wecan go ahead and close this issue then.
Cheers,
Jamal
