### ISSUE TITLE
idp proxy/protocolstub catalogue object incompatible with the specs

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-catalogue#57]
Hi,

The idp-proxy/protocolstub catalogue object is incompatible with the [specs](https://github.com/reTHINK-project/specs/tree/master/datamodel/core/hyperty-catalogue#protocol-stub-descriptor), some properties are missing.

When we update our idp-proxy or protocolstubs descriptor file, the catalogue broker doesn't return the same result as we have on that files;

We have this descriptor file, for the `slack.com`
```json
{
    "cguid": "5-c60b485c-b767-8be0-7f1f-64296e7bff4a3",
    "version": 0.7,
    "description": "Description of SlackProxyStub",
    "language": "Javascript",
    "type": "IDPProxys",
    "constraints": {},
    "interworking": true,
    "objectName": "slack.com",
    "configuration": {},
    "messageSchemas": [],
    "signature": "",
    "dataObjects": [],
    "accessControlPolicy": "somePolicy"
}
```
and the catalogue broker on UI returns this:
```json
{
    "cguid": "cb29d5e396cb9fe06a4d544f9104af81",
    "version": 0.7,
    "objectName": "slack.com",
    "description": "Description of SlackProxyStub",
    "sourcePackageURL": "hyperty-catalogue://catalogue.localhost/.well-known/sourcepackage/slack.com",
    "language": "Javascript",
    "messageSchemas": [ ],
    "configuration": { },
    "constraints": { }
}
```

**Comment by Endebert** [comment]
From your example I can gather that `accessControlPolicy`. `interworking` and `type` are missing. However:

* `accessControlPolicy` is not an attribute of Protocolstub according to the spec
* `interworking` is present when testing locally with the example you provided. Could you please check that you have a current version?
* `type` has never been supported up until now, only `hypertyType`. If you need support for this attribute, please tell me and I will add it. However, you set `"type": "IDPProxys"`, which is not according to the spec (it has to be an integer), so maybe you meant to set hypertyType instead?

**Comment by luistduarte** [comment]
I was looking to the specs and you are right at the some points

- accessControlPolicy has been removed
- interworking is present for protostub but not for idpProxy.. I am using latest version of [catalogue broker image](https://hub.docker.com/r/rethink/catalogue-broker/builds/bpkjp6sza4ezu3dxuxyta5h/) and interworking attribute is missing..

![screenshot from 2017-02-27 11 29 30](https://cloud.githubusercontent.com/assets/11315256/23359818/074f8fd6-fce0-11e6-8f65-5c256043350e.png)

**Comment by Endebert** [comment]
@luistduarte you are right. I have updated the model.json in the dev branch. I'm unable to test it right now, but that should fix the problem. Master branch will get the update probably tonight after I tested the changes.

**Comment by luistduarte** [comment]
@Endebert 

I'm still with troubles. 
When i am using docker image (last build) available in the docker-hub, interworking property for the IDPProxy is ignored, but using source-code and running catalogue-broker natively from repository dev-catalogue i can set interworking property as true on IDPProxy.

What is going on? any idea?

**Comment by Endebert** [comment]
@luistduarte I just tested the docker images on my workstation and they work properly.

You were only talking about the Catalogue Broker, have you also pulled the newest Catalogue Database docker image? Updates to both are needed in order for it to work. (otherwise the Database doesn't even serve the information to the Broker)

If it still doesn't work. I will make a new release with a new version. This should then be a good enough indicator to check if the newest code is being used.

**Comment by luistduarte** [comment]
@Endebert 

yes, I pulled the newest Catalogue Database [docker image](https://hub.docker.com/r/rethink/catalogue-database-rethinkdefault/)

Can you just test it with our [database](https://github.com/reTHINK-project/testbeds/tree/master/nodes/PT-node/development)? And check if on idpProxy interworking property is true for 'slack.com'.
![screenshot from 2017-03-02 14 32 55](https://cloud.githubusercontent.com/assets/11315256/23511502/2d6c6078-ff55-11e6-89e6-fe56071b5e31.png)

**Comment by Endebert** [comment]
Ah, I think I figured it out. I was just testing with rethink/catalogue-database. Since both rethink/catalogue-database and rethink/catalogue-database-rethinkdefault are built at the same time, the rethinkdefault image is probably one commit behind.

I just pushed a pseudo commit, I'm pretty sure this should fix it. Please pull the new docker image when the build is done.

**Comment by luistduarte** [comment]
Without success..

**Comment by Endebert** [comment]
Ok so there has to be some setup problem somewhere. Locally testing it again with rethink/catalogue-database-rethinkdefault and rethink/catalogue-broker was successful for me, i.e. interworking is displayed.

If I have time today, I will create a release with version 1.4.1, then we just have to look at the log prints to see if everything is up-to-date.

**Comment by luistduarte** [comment]
Interworking is displayed on Protostub or on IDPProxy? For Protustub it is working for me.. But for IDPProxy is not.
