### ISSUE TITLE
Installing Objects with different Constraints

### ISSUE THREAD

**Issue by luistduarte** [reTHINK-project/dev-catalogue#59]
How can we install objects with "same name" for being used on different runtimes.

Eg.
How can we define a default Protosub for Node and another One for Browser. I give you a simple diagram for be easy to understand

![diagram](https://cloud.githubusercontent.com/assets/11315256/23506543/c6d08a9c-ff40-11e6-804d-87e488efcb26.png)

Luís

**Comment by Endebert** [comment]
In case you want to have multiple "default" objects, you can simply declare them multiple times in the config or via launch option. For example, it could look something like this:

```
broker -default "protocolstub:node" -default "protocolstub:browser"
```
---
In case you want to have multiple objects using the same name (that is different from "default"), I believe you can simply define the same `objectName` in the description.json of both.

So, based on your example, both hyperties would have to have the `objectName` "H1".

But please note: The sourceCodeClassName in the sourcePackage.json must not be the same.
