### ISSUE TITLE
Catalogue assessment review

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-catalogue#66]
https://github.com/reTHINK-project/dev-catalogue/blob/master/doc/assessment/Readme.md

>> As the number of calls per connection is given as a parameter 

from Simon's review: *incomplete*

**Comment by emmelmann-fokus** [comment]
Please integrate the text as is.  I will make any needed corrections in word.

**Comment by pchainho** [comment]
The incomplete sentence is still there, now with a comment from @jmcrom

**Comment by emmelmann-fokus** [comment]
done in REV-0.10 on bscw
